In [4]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

In [5]:
df = pd.read_excel(r"C:\Users\admin\Downloads\Retail_Banking_Project\Merged_retail_banking.xlsx")

In [6]:
df.head()

,customer_id,age,region,preferred_channel,monthly_transactions_avg,avg_monthly_balance,num_products_held,digital_adoption_score,credit_card_issued,loan_taken,Age_group,Balance_Category,month,monthly_transactions,Month_Name,Active customer
0,CUST100007,56,South,ATM,23,37632,2,0.52,0,0,46-60,Medium,2022-01-01,15,January,yes
1,CUST100007,56,South,ATM,23,37632,2,0.52,0,0,46-60,Medium,2022-02-01,12,February,No
2,CUST100007,56,South,ATM,23,37632,2,0.52,0,0,46-60,Medium,2022-03-01,20,March,yes
3,CUST100007,56,South,ATM,23,37632,2,0.52,0,0,46-60,Medium,2022-04-01,21,April,yes
4,CUST100007,56,South,ATM,23,37632,2,0.52,0,0,46-60,Medium,2022-05-01,19,May,yes

In [7]:
print(df.columns)

Index(['customer_id', 'age', 'region', 'preferred_channel',
       'monthly_transactions_avg', 'avg_monthly_balance', 'num_products_held',
       'digital_adoption_score', 'credit_card_issued', 'loan_taken',
       'Age_group', 'Balance_Category', 'month', 'monthly_transactions',
       'Month_Name', 'Active customer'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24000 entries, 0 to 23999
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               24000 non-null  object
 1   age                       24000 non-null  int64
 2   region                    24000 non-null  object
 3   preferred_channel         24000 non-null  object
 4   monthly_transactions_avg  24000 non-null  int64
 5   avg_monthly_balance       24000 non-null  int64
 6   num_products_held         24000 non-null  int64
 7   digital_adoption_score    24000 non-null  float64
 8   credit_card_issued        24000 non-null  int64
 9   loan_taken                24000 non-null  int64
 10  Age_group                 23784 non-null  object
 11  Balance_Category          24000 non-null  object
 12  month                     24000 non-null  datetime64[ns]
 13  monthly_transactions      24000 non-null  int64
 14  Month_Name                24000 non-null  object
 15  Active customer           24000 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(7), object(7)
memory usage: 2.9+ MB

In [9]:
#check missing value
df.isnull().sum()

customer_id                   0
age                           0
region                        0
preferred_channel             0
monthly_transactions_avg      0
avg_monthly_balance           0
num_products_held             0
digital_adoption_score        0
credit_card_issued            0
loan_taken                    0
Age_group                   216
Balance_Category              0
month                         0
monthly_transactions          0
Month_Name                    0
Active customer               0
dtype: int64

In [10]:
#Handle Missing Values
numerical_cols = df.select_dtypes(include=['int64','float64']).columns

for col in numerical_cols:
    df[col].fillna(df[col].median(),inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_3312\3369218307.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(),inplace=True)

In [11]:
categorical_cols = df.select_dtypes(include=['object','category','bool']).columns

for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\admin\AppData\Local\Temp\ipykernel_3312\3225620178.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [12]:
#Verify Missing Values
print("Missing Values After Cleaning")
print(df.isnull().sum())

Missing Values After Cleaning
customer_id                 0
age                         0
region                      0
preferred_channel           0
monthly_transactions_avg    0
avg_monthly_balance         0
num_products_held           0
digital_adoption_score      0
credit_card_issued          0
loan_taken                  0
Age_group                   0
Balance_Category            0
month                       0
monthly_transactions        0
Month_Name                  0
Active customer             0
dtype: int64

In [13]:
#Remove Duplicate 
print("Duplicate Rows :", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("Shape After Removing Duplicates :", df.shape)

Duplicate Rows : 0
Shape After Removing Duplicates : (24000, 16)

In [14]:
#Remove Non-Informative Columns
columns_to_remove = [
    'customer_id',
    'month',
    'Month_Name'
]

df.drop(columns=columns_to_remove, inplace=True, errors='ignore')

In [15]:
#Select Features for Segmentation
selected_features = [

    'monthly_transactions_avg',
    'avg_monthly_balance',
    'num_products_held',
    'digital_adoption_score',
    'preferred_channel',
    'credit_card_issued',
    'loan_taken',
    'Active customer'
]

segmentation_df = df[selected_features].copy()

In [16]:
print(segmentation_df.head())

   monthly_transactions_avg  avg_monthly_balance  num_products_held  \
0                        23                37632                  2
1                        23                37632                  2
2                        23                37632                  2
3                        23                37632                  2
4                        23                37632                  2

   digital_adoption_score preferred_channel  credit_card_issued  loan_taken  \
0                    0.52               ATM                   0           0
1                    0.52               ATM                   0           0
2                    0.52               ATM                   0           0
3                    0.52               ATM                   0           0
4                    0.52               ATM                   0           0

  Active customer
0             yes
1              No
2             yes
3             yes
4             yes

In [17]:
#Encode Categorical Variables
categorical_features = [

    'preferred_channel',
    'credit_card_issued',
    'loan_taken',
    'Active customer'
]

segmentation_df = pd.get_dummies(

    segmentation_df,

    columns=categorical_features,

    drop_first=True
)

In [18]:
#Verify Data Types
print(segmentation_df.dtypes)

monthly_transactions_avg              int64
avg_monthly_balance                   int64
num_products_held                     int64
digital_adoption_score              float64
preferred_channel_Branch               bool
preferred_channel_Mobile App           bool
preferred_channel_Online Banking       bool
credit_card_issued_1                   bool
loan_taken_1                           bool
Active customer_yes                    bool
dtype: object

In [19]:
#Scale Features
scaler = StandardScaler()

segmentation_scaled = scaler.fit_transform(segmentation_df)

In [20]:
#Convert Back to DataFrame
segmentation_scaled = pd.DataFrame(

    segmentation_scaled,

    columns=segmentation_df.columns
)

In [21]:
print(segmentation_scaled.head())

   monthly_transactions_avg  avg_monthly_balance  num_products_held  \
0                     0.643            -0.797903           0.044953
1                     0.643            -0.797903           0.044953
2                     0.643            -0.797903           0.044953
3                     0.643            -0.797903           0.044953
4                     0.643            -0.797903           0.044953

   digital_adoption_score  preferred_channel_Branch  \
0                0.112372                 -0.592749
1                0.112372                 -0.592749
2                0.112372                 -0.592749
3                0.112372                 -0.592749
4                0.112372                 -0.592749

   preferred_channel_Mobile App  preferred_channel_Online Banking  \
0                     -0.560411                         -0.581969
1                     -0.560411                         -0.581969
2                     -0.560411                         -0.581969
3                     -0.560411                         -0.581969
4                     -0.560411                         -0.581969

   credit_card_issued_1  loan_taken_1  Active customer_yes
0             -0.645314     -0.507801             0.539588
1             -0.645314     -0.507801            -1.853265
2             -0.645314     -0.507801             0.539588
3             -0.645314     -0.507801             0.539588
4             -0.645314     -0.507801             0.539588

In [22]:
print(segmentation_scaled.describe().round(2))

       monthly_transactions_avg  avg_monthly_balance  num_products_held  \
count                  24000.00             24000.00           24000.00
mean                      -0.00                -0.00               0.00
std                        1.00                 1.00               1.00
min                       -3.15                -2.84              -0.98
25%                       -0.70                -0.69              -0.98
50%                       -0.03                 0.03               0.04
75%                        0.64                 0.68               1.07
max                        3.32                 3.11               2.09

       digital_adoption_score  preferred_channel_Branch  \
count                24000.00                  24000.00
mean                    -0.00                      0.00
std                      1.00                      1.00
min                     -1.69                     -0.59
25%                     -0.87                     -0.59
50%                      0.01                     -0.59
75%                      0.87                      1.69
max                      1.77                      1.69

       preferred_channel_Mobile App  preferred_channel_Online Banking  \
count                      24000.00                          24000.00
mean                           0.00                             -0.00
std                            1.00                              1.00
min                           -0.56                             -0.58
25%                           -0.56                             -0.58
50%                           -0.56                             -0.58
75%                           -0.56                              1.72
max                            1.78                              1.72

       credit_card_issued_1  loan_taken_1  Active customer_yes
count              24000.00      24000.00             24000.00
mean                   0.00          0.00                 0.00
std                    1.00          1.00                 1.00
min                   -0.65         -0.51                -1.85
25%                   -0.65         -0.51                 0.54
50%                   -0.65         -0.51                 0.54
75%                    1.55         -0.51                 0.54
max                    1.55          1.97                 0.54

In [23]:
print("Final Shape :", segmentation_scaled.shape)

Final Shape : (24000, 10)

In [24]:
segmentation_scaled.head()

,monthly_transactions_avg,avg_monthly_balance,num_products_held,digital_adoption_score,preferred_channel_Branch,preferred_channel_Mobile App,preferred_channel_Online Banking,credit_card_issued_1,loan_taken_1,Active customer_yes
0,0.643,-0.797903,0.044953,0.112372,-0.592749,-0.560411,-0.581969,-0.645314,-0.507801,0.539588
1,0.643,-0.797903,0.044953,0.112372,-0.592749,-0.560411,-0.581969,-0.645314,-0.507801,-1.853265
2,0.643,-0.797903,0.044953,0.112372,-0.592749,-0.560411,-0.581969,-0.645314,-0.507801,0.539588
3,0.643,-0.797903,0.044953,0.112372,-0.592749,-0.560411,-0.581969,-0.645314,-0.507801,0.539588
4,0.643,-0.797903,0.044953,0.112372,-0.592749,-0.560411,-0.581969,-0.645314,-0.507801,0.539588